# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

let
  uuid = uuid: "/dev/disk/by-uuid/${uuid}";
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "nvme" "usb_storage" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "boot.shell_on_fail" ];
  boot.supportedFilesystems = [ "btrfs" ];

  fileSystems =
    let
      main = uuid "5f24b2a6-643d-4abd-a3b2-61ee124700b5";
      esp = uuid "A2B8-4C6E";
      data = uuid "34668afb-7514-46cd-8c2c-0dcf19cd4742";

      btrfsOptions = [ "defaults" "autodefrag" "noatime" ];
    in
    {
      "/" = {
        device = "tmpfs";
        fsType = "tmpfs";
        options = [ "defaults" "size=4G" "mode=755" ];
      };

      "/media/main" = {
        device = main;
        fsType = "btrfs";
        options = [ "subvol=/" "ssd" ] ++ btrfsOptions;
        neededForBoot = true;
      };

      "/media/data" = {
        device = data;
        fsType = "btrfs";
        options = [ "subvol=/" "ssd" ] ++ btrfsOptions;
        neededForBoot = true;
      };

      "/persist" = {
        device = main;
        fsType = "btrfs";
        options = [ "subvol=root" "ssd" ] ++ btrfsOptions;
        neededForBoot = true;
      };

      "/persist-test" = {
        device = "overlay";
        fsType = "overlay";
        options = [
          "upperdir=/media/main/root"
          "lowerdir=/media/data/root"
          "workdir=/media/main/work"
        ];
        neededForBoot = true;
      };

      "/nix" = {
        device = main;
        fsType = "btrfs";
        options = [ "subvol=nix" "ssd" ] ++ btrfsOptions;
        neededForBoot = true;
      };

      "/boot" = {
        device = main;
        fsType = "btrfs";
        options = [ "subvol=boot" "ssd" ] ++ btrfsOptions;
        neededForBoot = true;
      };

      "/boot/efi" = {
        device = esp;
        fsType = "vfat";
        neededForBoot = true;
      };
    };

  swapDevices = [
    { device = uuid "b064d69c-0310-4a94-a0de-a4b358f54f9e"; }
  ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}
