# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  kmscon = {
    pname = "kmscon";
    version = "95ae9f869e01c5b26683c37a98a71b7551603d1c";
    src = fetchgit {
      url = "https://github.com/Aetf/kmscon";
      rev = "95ae9f869e01c5b26683c37a98a71b7551603d1c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1f7ifzafjrrwr5d477xjvx8n8rh2ljq9ms5c06xlb2cyi28jvgaf";
    };
  };
}
