# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  qtile = {
    pname = "qtile";
    version = "ffbf518ed7b2f376b77347fae09aa92514e89d4a";
    src = fetchFromGitHub ({
      owner = "qtile";
      repo = "qtile";
      rev = "ffbf518ed7b2f376b77347fae09aa92514e89d4a";
      fetchSubmodules = false;
      sha256 = "sha256-3FFMmLuw2cIViXCQJvTLpYUQli5u9s4qtDU6WHh4Te4=";
    });
    date = "2023-01-29";
  };
}
